title: "Robert Mounce Portfolio"
description: "A showcase of my data analytics projects and skills"
theme: jekyll-theme-cayman

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"
  - title: "Contact"
    url: "/contact/"

# Projects Section
projects:
  - title: "Bike Repair Analysis"
    description: "An analysis of bike repair data from a rental company, focusing on the time of repair, repair categories, and status updates."
    url: "/projects/bike-repair-analysis/"
    image: "/assets/images/bike-repair-analysis.jpg"

  - title: "Fantasy Football Data Analysis"
    description: "A Kaggle notebook project analyzing fantasy football data, including player performance and predictive modeling."
    url: "/projects/fantasy-football-data-analysis/"
    image: "/assets/images/fantasy-football-data-analysis.jpg"

  - title: "Development Economics in Qatar"
    description: "A project exploring labor and urbanization in Qatar, with a focus on immigration labor, economic diversification, and policy impacts."
    url: "/projects/development-economics-qatar/"
    image: "/assets/images/development-economics-qatar.jpg"

# About Section
about:
  title: "About Me"
  content: |
    I am an economics student at California State University, Long Beach, with a strong interest in data analytics and economic policy. I have experience in project management, data collection, and analysis, and I hold a Google Data Analytics Coursera certificate. My goal is to make an impact in economic policy and pursue a career as an economic consultant.

# Contact Section
contact:
  email: "your-email@example.com"
  linkedin: "https://www.linkedin.com/in/your-linkedin/"
  github: "https://github.com/your-github/"
